name: Run ADO to GitHub Sync with PowerShell

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Check out repo        
      uses: actions/checkout@v2
      
    - name: Setup PowerShell
      run: |
        Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser
        Invoke-WebRequest -Uri https://github.com/PowerShell/PowerShell/releases/latest/download/PowerShell-win-x64.zip -OutFile PowerShell.zip
        Expand-Archive -Path PowerShell.zip -DestinationPath $Env:ProgramFiles
        $PowerShellFolder = Get-ChildItem -Path $Env:ProgramFiles -Filter 'PowerShell-*' | Select-Object -Last 1
        Rename-Item -Path "$($PowerShellFolder.FullName)" -NewName 'PowerShell'
        Set-Variable -Name 'PATH' -Value "$($PowerShellFolder.FullName);$Env:PATH" -Scope 'Environment'
      
    - name: Run Sync Script
      run: |
        $ListObject = Get-Content -Path "${{ github.workspace }}/ADORepoList.json" | ConvertFrom-Json
        foreach ($object in $ListObject.RepoList) {
          Write-Host "--------------- Current syncing for repo $($object.AzureRepoName) ----------------------------------"
          Set-Location ${{ github.workspace }}
          & '.\SynADOtoGitHub.ps1' -GitHubDestinationPAT ${{ secrets.GITHUBDESTINATIONPAT }} -ADOSourcePAT ${{ secrets.ADOSOURCEPAT }} -AzureRepoName $($object.AzureRepoName) -ADOCloneURL $($object.ADOCloneURL) -GitHubCloneURL $($object.GitHubCloneURL)
          Write-Host "---------------------------------------------------------------------------------------------------"
        }
