name: Run ADO to GitHub Sync with PowerShell

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Check out repo        
      uses: actions/checkout@v2
      
    - name: Setup PowerShell
      uses: actions/setup-powershell@v2
      with:
        pwsh-version: '7.x'  # Replace with the desired PowerShell version

    - name: Run Sync Script
      run: |
        $ListObject = Get-Content -Path "${{ github.workspace }}/ADORepoList.json" | ConvertFrom-Json
        foreach ($object in $ListObject.RepoList) {
          Write-Host "--------------- Current syncing for repo $($object.AzureRepoName) ----------------------------------"
          Set-Location ${{ github.workspace }}
          & '.\SynADOtoGitHub.ps1' -GitHubDestinationPAT ${{ secrets.GITHUBDESTINATIONPAT }} -ADOSourcePAT ${{ secrets.ADOSOURCEPAT }} -AzureRepoName $($object.AzureRepoName) -ADOCloneURL $($object.ADOCloneURL) -GitHubCloneURL $($object.GitHubCloneURL)
          Write-Host "---------------------------------------------------------------------------------------------------"
        }
